import { StyleSheet } from 'react-native';
const styleBoxCalc=StyleSheet.create(
    {
        container:{
            flex:1,
            justifyContent:'center',
            marginTop:10,
            marginBottom:15,
        },
        card:{
            backgroundColor:'#96D9D2',
            borderRadius:20,
            marginLeft:'auto',
            marginRight:'auto',
            width:'90%',
            paddingTop:25,
            paddingBottom:25,
            justifyContent:'center',
        },
        cardTitle:{
            marginLeft:'auto',
            marginRight:'auto',
            paddingBottom:10,
            fontWeight:'bold',
        },
        cardContainer:{
            borderTopColor:'#000',
            borderStyle:'dotted',
            borderTopWidth:3,
            borderBottomWidth:3,
            width:'90%',
            marginLeft:'auto',
            marginRight:'auto',
            marginBottom:10
        },
        cardTextBox:{
            marginLeft:'auto',
            marginRight:'auto',
        },
        cardText:{
            paddingTop:10,
        },
        cardInto:{
            backgroundColor:'#04BFAD',
            padding:10,
            borderRadius:8,
            marginTop:10,
            marginBottom:10,
            width:'80%',
            marginRight:'auto',
            marginLeft:'auto',
        },
        cardIntoText:{
            marginLeft:'auto',
            marginRight:'auto',
            fontWeight:'bold',
        },
        cardButtonsFooter:{
            flexDirection:'row',
            alignItems:'center',
            justifyContent:'space-around',
        },
        teste:{
            fontWeight:'bold'
        }
    }
)
export default styleBoxCalc;